# Generated by Django 2.0.12 on 2020-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180505_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='licence',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
