# Generated by Django 2.0.12 on 2020-04-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_licence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='licence',
            new_name='license',
        ),
    ]
